

import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/authOptions";

export async function POST(req: NextRequest) {
  try {
    const session = await getServerSession(authOptions);
    const adminId = session?.user?.id ? parseInt(session.user.id) : null;

    if (!adminId) {
      return NextResponse.json(
        { error: "Unauthorized: Admin session required" },
        { status: 401 }
      );
    }

    const defaultSettings = [
  // Client Email Settings
  {
    key: 'client_from_email',
    value: '',
    type: 'email',
    category: 'client_email_settings',
    label: 'From Email Address',
    description: 'Email address used as sender for all client-related outgoing emails',
    isRequired: true,
    defaultValue: '',
    sortOrder: 1,
  },
  {
    key: 'client_smtp_host',
    value: '',
    type: 'text',
    category: 'client_email_settings',
    label: 'SMTP Host',
    description: 'The SMTP server used to send client-related emails (e.g., smtp.gmail.com)',
    isRequired: true,
    defaultValue: '',
    sortOrder: 2,
  },
  {
    key: 'client_smtp_port',
    value: '587',
    type: 'number',
    category: 'client_email_settings',
    label: 'SMTP Port',
    description: 'The port number used to connect to the SMTP server (e.g., 587 for TLS)',
    isRequired: true,
    defaultValue: '587',
    sortOrder: 3,
  },
  {
    key: 'client_smtp_password',
    value: '',
    type: 'password',
    category: 'client_email_settings',
    label: 'SMTP App Password',
    description: 'App password used to authenticate with the SMTP server for client emails',
    isRequired: true,
    defaultValue: '',
    sortOrder: 4,
  },
  {
    key: 'client_admin_email',
    value: '',
    type: 'email',
    category: 'client_email_settings',
    label: 'Admin Notification Email',
    description: 'Email address where client-related system alerts or notifications will be sent',
    isRequired: true,
    defaultValue: '',
    sortOrder: 5,
  },

  // Client Form Metadata
  {
    key: 'client_company_website',
    value: '',
    type: 'url',
    category: 'client_form_metadata',
    label: 'Company Website',
    description: 'Company website URL that appears on client forms',
    isRequired: true,
    defaultValue: '',
    sortOrder: 1,
  },
  {
    key: 'client_review_date',
    value: '',
    type: 'date',
    category: 'client_form_metadata',
    label: 'Review Date',
    description: 'Default review date for client forms',
    isRequired: true,
    defaultValue: '',
    sortOrder: 2,
  },

  // Form IDs
  {
    key: 'client_intake_form_id',
    value: '',
    type: 'text',
    category: 'form_ids',
    label: 'Client Intake Form ID',
    description: 'Unique identifier for client intake forms',
    isRequired: true,
    defaultValue: '',
    sortOrder: 1,
  },
  {
    key: 'home_visit_form_id',
    value: '',
    type: 'text',
    category: 'form_ids',
    label: 'Home Visit Risk Assessment ID',
    description: 'Unique identifier for home visit risk assessment forms',
    isRequired: true,
    defaultValue: '',
    sortOrder: 2,
  },
  {
    key: 'person_centre_plan_form_id',
    value: '',
    type: 'text',
    category: 'form_ids',
    label: 'Person Centre Plan ID',
    description: 'Unique identifier for person centre plan forms',
    isRequired: true,
    defaultValue: '',
    sortOrder: 3,
  },
  {
    key: 'sa_delivery_of_supports',
    value: '',
    type: 'text',
    category: 'form_ids',
    label: 'SA Delivery of Supports ID',
    description: 'Unique identifier for SA Delivery of Supports forms',
    isRequired: true,
    defaultValue: '',
    sortOrder: 4,
  },
  {
    key: 'participant_risk_assessment',
    value: '',
    type: 'text',
    category: 'form_ids',
    label: 'Participant Risk Assessment ID',
    description: 'Unique identifier for Participant Risk Assessment forms',
    isRequired: true,
    defaultValue: '',
    sortOrder: 5,
  },
  {
    key: 'emergency_drill',
    value: '',
    type: 'text',
    category: 'form_ids',
    label: 'Emergency Drill ID',
    description: 'Unique identifier for Emergency Drill forms',
    isRequired: true,
    defaultValue: '',
    sortOrder: 6,
  },
  {
    key: 'individual_risk_assessment',
    value: '',
    type: 'text',
    category: 'form_ids',
    label: 'Individual Activity Risk Assessment ID',
    description: 'Unique identifier for Individual Activity Risk Assessment forms',
    isRequired: true,
    defaultValue: '',
    sortOrder: 7,
  },
  {
    key: 'welcome_form',
    value: '',
    type: 'text',
    category: 'form_ids',
    label: 'Welcome Form ID',
    description: 'Unique identifier for Welcome form',
    isRequired: true,
    defaultValue: '',
    sortOrder: 8,
  },
  {
    key: 'multi_disciplinary_meeting',
    value: '',
    type: 'text',
    category: 'form_ids',
    label: 'Multi Disciplinary Meeting ID',
    description: 'Unique identifier for Multi Disciplinary Meeting form',
    isRequired: true,
    defaultValue: '',
    sortOrder: 9,
  },
  {
    key: 'support_action_plan',
    value: '',
    type: 'text',
    category: 'form_ids',
    label: 'Support Co-ordination Action Plan ID',
    description: 'Unique identifier for Support Co-ordination Action Plan form',
    isRequired: true,
    defaultValue: '',
    sortOrder: 10,
  },
  {
    key: 'schedule_of_supports',
    value: '',
    type: 'text',
    category: 'form_ids',
    label: 'Schedule of Supports Form ID',
    description: 'Unique identifier for Schedule of Supports form',
    isRequired: true,
    defaultValue: '',
    sortOrder: 11,
  },
  {
    key: 'sa_support_coordination',
    value: '',
    type: 'text',
    category: 'form_ids',
    label: 'Service Agreement Support Co-Ordination ID',
    description: 'Unique identifier for Service Agreement Support Co-Ordination forms',
    isRequired: true,
    defaultValue: '',
    sortOrder: 12,
  },

  // Staff Form IDs
  {
    key: 'employee_details_form_id',
    value: '',
    type: 'text',
    category: 'staff_form_ids',
    label: 'Employee Details Form ID',
    description: 'Unique identifier for Employee Details forms',
    isRequired: true,
    defaultValue: '',
    sortOrder: 1,
  },
  {
    key: 'employee_welcome_form_id',
    value: '',
    type: 'text',
    category: 'staff_form_ids',
    label: 'Employee Welcome Pack Form ID',
    description: 'Unique identifier for Employee Welcome Pack forms',
    isRequired: true,
    defaultValue: '',
    sortOrder: 2,
  },
  {
    key: 'support_worker_form_id',
    value: '',
    type: 'text',
    category: 'staff_form_ids',
    label: 'Position Description Form ID',
    description: 'Unique identifier for Position Description forms',
    isRequired: true,
    defaultValue: '',
    sortOrder: 3,
  },
  {
    key: 'pre_employment_medical_form_id',
    value: '',
    type: 'text',
    category: 'staff_form_ids',
    label: 'Pre-Employment Medical Form ID',
    description: 'Unique identifier for Pre-Employment Medical forms',
    isRequired: true,
    defaultValue: '',
    sortOrder: 4,
  },
  {
    key: 'bullying_harassment_training_form_id',
    value: '',
    type: 'text',
    category: 'staff_form_ids',
    label: 'Bullying and Harassment Training Form ID',
    description: 'Unique identifier for Bullying and Harassment Training forms',
    isRequired: true,
    defaultValue: '',
    sortOrder: 5,
  },
  {
    key: 'bullying_training_form_id',
    value: '',
    type: 'text',
    category: 'staff_form_ids',
    label: 'Bullying Training Form ID',
    description: 'Unique identifier for Bullying Training forms',
    isRequired: true,
    defaultValue: '',
    sortOrder: 6,
  },
  {
    key: 'ndis_code_of_conduct_form_id',
    value: '',
    type: 'text',
    category: 'staff_form_ids',
    label: 'NDIS Code of Conduct Form ID',
    description: 'Unique identifier for NDIS Code of Conduct forms',
    isRequired: true,
    defaultValue: '',
    sortOrder: 7,
  },
  {
    key: 'fair_work_information_form_id',
    value: '',
    type: 'text',
    category: 'staff_form_ids',
    label: 'Fairwork Information Statements Form ID',
    description: 'Unique identifier for Fairwork Information Statements forms',
    isRequired: true,
    defaultValue: '',
    sortOrder: 8,
  },
  {
    key: 'orientation_form_id',
    value: '',
    type: 'text',
    category: 'staff_form_ids',
    label: 'Staff Orientation Form ID',
    description: 'Unique identifier for Staff Orientation forms',
    isRequired: true,
    defaultValue: '',
    sortOrder: 9,
  },
  {
    key: 'conflict_of_interest_form_id',
    value: '',
    type: 'text',
    category: 'staff_form_ids',
    label: 'Conflict of Interest Form ID',
    description: 'Unique identifier for Conflict of Interest forms',
    isRequired: true,
    defaultValue: '',
    sortOrder: 10,
  },
  {
    key: 'documentation_acknowledgement_form_id',
    value: '',
    type: 'text',
    category: 'staff_form_ids',
    label: 'Documentation Acknowledgement Form ID',
    description: 'Unique identifier for Documentation Acknowledgement forms',
    isRequired: true,
    defaultValue: '',
    sortOrder: 11,
  },
  {
    key: 'vehicle_safety_inspection_form_id',
    value: '',
    type: 'text',
    category: 'staff_form_ids',
    label: 'Vehicle Safety Inspection Form ID',
    description: 'Unique identifier for Vehicle Safety Inspection forms',
    isRequired: true,
    defaultValue: '',
    sortOrder: 12,
  },

  // Staff Email Settings
  {
    key: 'staff_from_email',
    value: '',
    type: 'email',
    category: 'staff_email_settings',
    label: 'From Email Address',
    description: 'Email address used as sender for all staff-related outgoing emails',
    isRequired: true,
    defaultValue: '',
    sortOrder: 1,
  },
  {
    key: 'staff_smtp_host',
    value: '',
    type: 'text',
    category: 'staff_email_settings',
    label: 'SMTP Host',
    description: 'The SMTP server used to send staff-related emails (e.g., smtp.gmail.com)',
    isRequired: true,
    defaultValue: '',
    sortOrder: 2,
  },
  {
    key: 'staff_smtp_port',
    value: '587',
    type: 'number',
    category: 'staff_email_settings',
    label: 'SMTP Port',
    description: 'The port number used to connect to the SMTP server (e.g., 587 for TLS)',
    isRequired: true,
    defaultValue: '587',
    sortOrder: 3,
  },
  {
    key: 'staff_smtp_password',
    value: '',
    type: 'password',
    category: 'staff_email_settings',
    label: 'SMTP App Password',
    description: 'App password used to authenticate with the SMTP server for staff emails',
    isRequired: true,
    defaultValue: '',
    sortOrder: 4,
  },
  {
    key: 'staff_admin_email',
    value: '',
    type: 'email',
    category: 'staff_email_settings',
    label: 'Admin Notification Email',
    description: 'Email address where staff-related system alerts or notifications will be sent',
    isRequired: true,
    defaultValue: '',
    sortOrder: 5,
  },

  // Staff Form Metadata
  {
    key: 'staff_company_website',
    value: '',
    type: 'url',
    category: 'staff_form_metadata',
    label: 'Company Website',
    description: 'Company website URL that appears on staff forms',
    isRequired: true,
    defaultValue: '',
    sortOrder: 1,
  },
  {
    key: 'staff_review_date',
    value: '',
    type: 'date',
    category: 'staff_form_metadata',
    label: 'Review Date',
    description: 'Default review date for staff forms',
    isRequired: true,
    defaultValue: '',
    sortOrder: 2,
  },
];

    const upsertPromises = defaultSettings.map((setting : any ) =>
      prisma.appSettings.upsert({
        where: {
          key_adminId: {
            key: setting.key,
            adminId: adminId,
          },
        },
        update: {
          label: setting.label,
          description: setting.description,
          type: setting.type,
          category: setting.category,
          isRequired: setting.isRequired,
          defaultValue: setting.defaultValue,
          sortOrder: setting.sortOrder,
          isActive: true,
          updatedAt: new Date(),
        },
        create: {
          key: setting.key,
          value: setting.value,
          type: setting.type,
          category: setting.category,
          label: setting.label,
          description: setting.description,
          isRequired: setting.isRequired,
          defaultValue: setting.defaultValue,
          sortOrder: setting.sortOrder,
          isActive: true,
          adminId: adminId,
        },
      })
    );

    const results = await prisma.$transaction(upsertPromises);

    return NextResponse.json({
      success: true,
      message: `Initialized ${results.length} admin-specific settings`,
      settings: results,
      categories: [...new Set(results.map((s: any) => s.category))],
    });
  } catch (error: any) {
    console.error("Error initializing settings:", error);
    return NextResponse.json(
      { error: "Failed to initialize settings", details: error.message },
      { status: 500 }
    );
  }
}
